services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./springdb.sql:/docker-entrypoint-initdb.d/springdb.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend/demo
    container_name: spring_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "9090:9090"
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: always
